### ISSUE TITLE
Add icon resource

### ISSUE THREAD

**Issue by expert3vision** [fincs/Ahk2Exe#25]
@fincs 
I have noticed that adding icon resource through compile directives is not currently supported.
In case this is because you are not sure how to do this through UpdateResource WinAPI function there is an article explaining this here: http://www.codeguru.com/cpp/w-p/win32/tutorials/article.php/c12873/Hacking-Icon-Resources.htm
Specifically:
"... In resources, icons are split into several RC_ICON resources and a RC_GROUP_ICON. A RC_ICON entry is basically the above ICON IMAGE. RC_GROUP_ICON contains the ICON HEADER and DIRECTORY ENTRIES with a single modification: The DWORD ImageOffset becomes WORD ResourceID."

Thanks for the comment in code on how to handle bitmap resources. I would have never guest you have to remove the BMP header.

**Comment by joedf** [comment]
I think it's just not implemented yet, or it was forgotten. But you can still do it manually by using a label that is never called containing a FileInstall of the icons you want included. Then you can use DllCall to FindResource, LockResource, etc.

**Comment by fincs** [comment]
I do know how icon resources work (in fact, there's already some icon resource editing code that Ahk2Exe uses for changing the program icon); I just haven't had time to actually implement it (there also are some considerations related to the IDs of the individual icons inside a group that must be taken into account).

**Comment by joedf** [comment]
Related.
https://github.com/fincs/Ahk2Exe/commit/a00a3ea324a081cd3365611cf2db9c688cb977df
