### ISSUE TITLE
Icon quality in compiled script

### ISSUE THREAD

**Issue by cyruz-git** [fincs/Ahk2Exe#26]
Hi fincs,
when you compile a script with an icon, the quality of the icon is consistently worse compared to the same icon in the uncompiled script set with the menu command.

I'm not sure this depends from Ahk2Exe, because from what I see in the code you just replace the main AHK icon with the custom one. Sorry if this is not pertinent.

**Comment by fincs** [comment]
Huh?

**Comment by cyruz-git** [comment]
Ahahaha :D
Sorry to bother you here, I thought it would be better to open a issue directly, so that it could eventually be dismissed quickly if it is a non-problem. Attached you find a zoomed image showing how it looks in the script and in the compiled version.

![crop](https://cloud.githubusercontent.com/assets/622306/5883575/00a9acd0-a354-11e4-8517-9684ca074c67.png)

I was trying to understand why this difference in quality and I thought that maybe the "Menu, Tray, Icon" command uses a different way to load the icon than the default way used when the script is started. What do you think?

**Comment by fincs** [comment]
Looks like an AutoHotkey issue, not an Ahk2Exe issue. I think Lexikos indirectly fixed this in one recent [test build](http://ahkscript.org/boards/viewtopic.php?f=24&t=5802).

> Improved selection of icon size when loading icons from DLL/EXE files.
