### ISSUE TITLE
ScriptParser.ahk

### ISSUE THREAD

**Issue by HotKeyIt** [fincs/Ahk2Exe#27]
In ScriptParser.ahk line 93 
if tline ~= "^\w+\s+(:=|+=|-=|\*=|/=|//=|\.=|\|=|&=|\^=|>>=|<<=)"
should be:
if tline ~= "^\w+\s+(:=|\\+=|-=|\*=|/=|//=|\.=|\|=|&=|\^=|>>=|<<=)"

**Comment by fincs** [comment]
I had to look at the raw Markdown source of your post, but I see you added a \\ backslash to the +. I'll fix it.

**Comment by HotKeyIt** [comment]
Sorry, I corrected above.

**Comment by joedf** [comment]
Close issue. Fixed: https://github.com/fincs/Ahk2Exe/commit/ec4841e61cb25c19e5309a460d780873a3e5db27

**Comment by joedf** [comment]
Closed?
