### ISSUE TITLE
ScriptParser.ahk

### ISSUE THREAD

**Issue by HotKeyIt** [fincs/Ahk2Exe#28]
The /iLib call must be run using ScriptText and not original script because we might be using /*@Ahk2Exe-Keep, see changes here: https://github.com/HotKeyIt/Ahk2Exe/commit/d355d9ea5481dc52ac4bee5a751d47f9a6fe76a5?diff=unified#diff-73478a1b9d1c9b43c7db52c6a87efc10R142

**Comment by fincs** [comment]
See 90944144c104ad65200e00f74de3cb7263168fcf. This was fixed awhile ago.
