### ISSUE TITLE
Compile messages without GUI?

### ISSUE THREAD

**Issue by highend** [fincs/Ahk2Exe#29]
Hi,

I'm compiling my .ahk scripts within Sublime Text 3 (with the help of a build script (a .bat file) that invokes ahk2exe with the necessary /in /out and /icon switch).

Is there any way to get the compiler (error) messages back into the console view of Sublime Text instead of getting a normal popup window? Regex parsing the output inside the console view allows to directly go to the line of an error for example.

Sublime Text 3 can be used as a portable application so if you'd like to take a look at it for yourself...

Tia,
Highend

**Comment by joedf** [comment]
Yes, an errorlevel exit would be quite nice for Ahk2Exe.
I have request for that here: https://github.com/fincs/Ahk2Exe/issues/16
but, no response...

**Comment by joedf** [comment]
Close this issue?
