### ISSUE TITLE
Add more specificity to script syntax errors message.

### ISSUE THREAD

**Issue by G33kDude** [fincs/Ahk2Exe#34]
Had a guy in the IRC today asking why he no longer got a specific error message when his script contains syntax errors. I pinpointed the change to commit 212f0170ff20deaa9cca984a30e89f5873421937 . I suggest passing the error message from `/ErrorStdOut` into the `extra` parameter of `Util_Error`.

**Comment by joedf** [comment]
So, essentially a more specific and elaborate error message. Good idea! :+1:
