### ISSUE TITLE
Usage in readme.txt points to l.autohotkey.net

### ISSUE THREAD

**Issue by TLMcode** [fincs/Ahk2Exe#36]
Not sure if this is something you deal with fincs but a user tried the link under usage in the readme.txt file ( from here: http://ahkscript.org/download/ahk2exe.zip ).
The broken link in question: Online:   http://l.autohotkey.net/docs/Scripts.htm#ahk2exe

**Comment by joedf** [comment]
hmm, I think this is actually done with lexikos' script.
@Lexikos (mentioning him here, to notify)

**Comment by Lexikos** [comment]
It will be fixed by the next update.
