### ISSUE TITLE
[Ahk2Exe-Edge]Directive SetVersion is not working in 32bit - Ansi version

### ISSUE THREAD

**Issue by dmacoder** [fincs/Ahk2Exe#44]
Could you test compiling Ahk2Exe.ahk to Ahk2Exe.exe by using Ansi Version?
Directive SetVersion is not working in 32bit - Ansi version
 szKey Value is not same as follows 
 Unicode Ver : VS_VERSION_INFO
 Ansi ver : V
 So occuring out of memory.
Error in #include VersionRes.ahk
 Out of memory 
 026: while addr < addrLimit
 027: {
 028 : size := (NumGet(addr+0, "Ushort") + 3) &~3, blabla~~

 class VersionRes
 {
 Name := ""
 ,Data := ""
 ,IsText := true
 ,DataSize := 0
 ,Children := []
__New(addr := 0)
{
    if !addr
        return this
    wLength := NumGet(addr+0, "UShort"), addrLimit := addr + wLength, addr += 2
    ,wValueLength := NumGet(addr+0, "UShort"), addr += 2
    ,wType := NumGet(addr+0, "UShort"), addr += 2
    ;Need to modify below
            szKey := StrGet(addr), addr += 2*(StrLen(szKey)+1), addr := (addr+3)&~3

    ObjSetCapacity(this, "Data", size := wValueLength*(wType+1))
     ;Check Value is Correct

msgbox,% "wLength : " wLength " nwValueLength : " wValueLength " nszKey : " szKey "`nwType : " wType
 ;szKey Value is not Correct. as follows Unicode Ver : VS_VERSION_INFO , Ansi ver : V
 ;so occuring out of memory
    this.Name := szKey
    ,this.DataSize := wValueLength
    ,this.IsText := wType
    ,DllCall("msvcrt\memcpy", "ptr", this.GetDataAddr(), "ptr", addr, "ptr", size, "cdecl"), addr += size, addr := (addr+3)&~3
     ;if wType
    ;ObjSetCapacity(this, "Data", -1)
    while addr < addrLimit
    {
        size := (NumGet(addr+0, "UShort") + 3) & ~3
        ,this.Children.Insert(new VersionRes(addr))
        ,addr += size
    }
}

_NewEnum()
{
    return this.Children._NewEnum()
}

AddChild(node)
{
    this.Children.Insert(node)
}

GetChild(name)
{
    for k,v in this
        if v.Name = name
            return v
}

GetText()
{
    if this.IsText
        return this.Data
}

SetText(txt)
{
    this.Data := txt
    ,this.IsText := true
    ,this.DataSize := StrLen(txt)+1
}

GetDataAddr()
{
    return ObjGetAddress(this, "Data")
}

Save(addr)
{
    orgAddr := addr
    ,addr += 2
    ,NumPut(ds:=this.DataSize, addr+0, "UShort"), addr += 2
    ,NumPut(it:=this.IsText, addr+0, "UShort"), addr += 2
    ,addr += 2*StrPut(this.Name, addr+0, "UTF-16")
    ,addr := (addr+3)&~3
    ,realSize := ds*(it+1)
    ,DllCall("msvcrt\memcpy", "ptr", addr, "ptr", this.GetDataAddr(), "ptr", realSize, "cdecl"), addr += realSize
    ,addr := (addr+3)&~3
    for k,v in this
        addr += v.Save(addr)
    size := addr - orgAddr
    ,NumPut(size, orgAddr+0, "UShort")
    return size
}

}

;@Ahk2Exe-SetName Ahk2Exe
 ;@Ahk2Exe-SetDescription AutoHotkey Script Compiler
 ;@Ahk2Exe-SetCopyright Copyright (c) since 2004
 ;@Ahk2Exe-SetCompanyName AutoHotkey
 ;@Ahk2Exe-SetOrigFilename Ahk2Exe.ahk
 ;@Ahk2Exe-SetMainIcon Ahk2Exe.ico

;@Ahk2Exe-SetVersion 1.0.0.1

I had to check value is correct.
 msgbox,% "wLength : " wLength " nwValueLength : " wValueLength " nszKey : " szKey "`nwType : " wType
 szKey Value is not same as follows 
 Unicode Ver : VS_VERSION_INFO
 Ansi ver : V
 So occuring out of memory.
 Error in #include VersionRes.ahk
 Out of memory 
 026: while addr < addrLimit
 027: {
 028 : size := (NumGet(addr+0, "Ushort") + 3) &~3, blabla~~

I modify below and szKey Value is correct.
 szKey := StrGet(addr,"UTF-16")
 and then Compilation is complete without out of memory.
 Set Version is replaced correctly.
 But, Set Description is not correct as follows. (Such as Text is not correct ; likes wType=1)
畁潴潈歴祥匠牣灩⁴潃灭汩牥䘀潲卭牴慥Ɑ摇灩畬屳摇灩牃慥@��FileVersion 
 This script is difficult to understand. I can't fix it anymore
 Can you do fix it?

**Comment by joedf** [comment]
Why use ANSI? Is the file saved as UTF-8?

**Comment by dmacoder** [comment]
Because some scripts written for AutoHotkey_B will function correctly on the ANSI version of AutoHotkey_L but fail on Unicode versions.
And I have Ansi Version of DataBase as follows .
Ansi
\u00BD\u00C3\u00B0\u00A3
Unicode
\uC2DC\uAC04
Ansi
\u00BF\u00AA\u00BC\u00F8\u00C0\u00D4\u00C0\u00E5
Unicode
\uC5ED\uC21C\uC785\uC7A5
-----------------------------------------
Anyway, Yes It is saved as UTF-8 (It just Ahk2Exe.ahk - edge)
Could you test compiling Ahk2Exe.ahk to Ahk2Exe.exe by using Ansi Version?
It is occuring out of memory.

**Comment by joedf** [comment]
Yes okay. You can't expect UTF-8 files to work with ANSI. Unicode character take more memory space than ASCII characters do. Remove all unicode characters and save it as a normal ASCII file.

**Comment by dmacoder** [comment]
Thanks for reply.
HotKeyIt fixed it.
https://github.com/HotKeyIt/ahkdll-v1-release/blob/master/Compiler/Lib/VersionRes.ahk
