### ISSUE TITLE
scripts compiled by ahk2exe are being catched by AVG anti-virus.

### ISSUE THREAD

**Issue by Le2222** [fincs/Ahk2Exe#52]
I have used this software without any issues in past (I used to have the same anti-virus too). Now, when I compile the ahk script the AVG takes it as a threat and move it to quarantine.

AVG says: 'Win-32:Evo-gen [Susp]' threat level: medium

**Comment by fincs** [comment]
This is a false positive, and it's 100% the fault of AV vendors (not ours). I'd recommend getting rid of 3rd party AVs if you have Windows 8 or newer.

**Comment by Le2222** [comment]
additional info:
if i use the previous compiler that cames with autohotkey 1.1.29, AVG says my file is safe.

**Comment by JnLlnd** [comment]
This is still a false positive. Anti-virus software use "approximative" algorithms to detect viruses (for performance concerns) and this result in a certain percentage of executable to be considered infected by error. The result can change for each update of the antivirus signature file and for each update of the tested files. It's a real pain and there is nothing AHK developers can do against it.

If you do not want to get rid of AVG, you can whitelist AHK in AVG config. And if you distribute your software on systems you do not own/control, the only way I found to reduce (not eliminate) false positives is to sign the compiled files with a certificate ($). If your project justifies it.

**Comment by Le2222** [comment]
Just to let it clear: I do think it is a false positive and even reported it as a false positive to AVG, I am not complaining about the issue with you, I am just sharing my experience to let you guys aware about this fact (maybe there's some change from version 1.1.29 to 1.1.30 that triggers this behavior on AVG). Thanks about the certificate ($) info, I didn't know about that (I made a rollback to v1.1.29 to workaround the situation instead).
